# -*- coding: utf-8 -*-
"""ANALYSIS 3 CARS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMnTke0KduJFw4XF5wp4FZBa3eHbWhNR

ANALYSIS 3

PLOTTING GRAPHS AND COMPARING THEM WITH THEIR ENGINE SIZE,PRICE,TYPE
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# importing required libraries
import os
import subprocess
import stat
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
sns.set(style="white")

# absolute path till parent folder
abs_path = os.getcwd()
path_array = abs_path.split("/")
path_array = path_array[:len(path_array)-1]
homefolder_path = ""
for i in path_array[1:]:
    homefolder_path = homefolder_path + "/" + i

df = pd.read_csv("CARS.csv")

plt.figure(figsize=(16,7))
sns.countplot(data=df, y='Type',alpha=.6,color='darkblue')
plt.title('Cars by type',fontsize=20)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('')
plt.ylabel('');

"""SUV's Sedans seems to be the dominating car types"""

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x='MSRP', y='Type', palette='viridis')
plt.title('Box plot of Price of every body type',fontsize=18)
plt.ylabel('')
plt.yticks(fontsize=14)
plt.xticks([i for i in range(0,800000,100000)],[f'{i:,}$' for i in range(0,800000,100000)],fontsize=14);

"""It's Clear that Car body type strongly affect the price

Now we check cars by EngineSize
"""

plt.figure(figsize=(20,6))
sns.countplot(data=df, x='EngineSize',alpha=.6, color='darkblue')
plt.title('Cars count by Engine Size',fontsize=18)
plt.xlabel('EngineSize', fontsize=16)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.ylabel('');

"""Mostly cars have engine size 3

Now We check the Horsepower of cars
"""

plt.figure(figsize=(14,6))
sns.histplot(data=df, x='Horsepower',alpha=.6, color='darkblue')
plt.title('Cars by engine size (in CC)',fontsize=18);
plt.xticks(fontsize=13);
plt.yticks(fontsize=13);

"""Performing a 5 number summary (min, lower quartile, median, upper quartile, max)

Next step is to perform a 5-number summary for the numeric data. As discussed earlier the numeric data, in this case, are MSRP, Engine Size, Horsepower, Cylinders, Horsepower, MPG_City, MPG_Highway, Weight, Wheelbase, and Length. The five-number summary includes minimum, lower quartile, median, upper quartile, and the maximum values all these values can be obtained by using the describe method.


"""

df.describe()